import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { Banner } from "../components/Banner";
import { BusinessOwners } from "../components/BusinessOwners";
import { Customers } from "../components/Customers";
import { MobileNavbar } from "../components/Header/MobileNavbar";
import Offers from "../components/Offers";
import { PopularBusiness } from "../components/PopularBusiness";
import PopularServices from "../components/PopularServices";
import SearchPanel from "../components/SearchPanel";

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch(
    `https://635a578638725a1746c39676.mockapi.io/bizreview/api/v1/categories`
  );

  const data = await res.json();
  return {
    props: {
      data,
    },
  };
};

const Home: NextPage = ({ data }: any) => {
  console.log(data)
  return (
    <>
      <Head>
        <title>bizreview</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Banner />
      <MobileNavbar />
      <SearchPanel />
      <PopularServices {...data} />
      <BusinessOwners />
      <Offers />
      <PopularBusiness />
      <Customers />
    </>
  );
};
export default Home;
